### ISSUE TITLE
Missing dependencies when compiling on Ubuntu 18.04

### ISSUE THREAD

**Issue by HermitSun** [CamFlow/camflow-dev#115]
I followed 'the building from source' instructions on a fresh Ubuntu Server 18.04.1 LTS machine. However, some dependencies still missed, including `uthash.h`, `ini.h` and `MQTTClient.h`.

And after I manually installed `uthash-dev`, `libinih-dev` and `paho.mqtt.c`，it can work.

Should these denpendencies be included in the documentation?

**Comment by tfjmp** [comment]
Thank you, I updated the dependencies on the website!

I suggest Fedora instead of Ubuntu.

**Comment by HermitSun** [comment]
Thank you for your rapid reply. 
I just want to know whether it can work on Ubuntu :-) Because after I installed all the packages for Ubuntu on packagecloud.io, it cannot work properly, and prompted that `libinih.so.0` cannot be found.
I have seen the lost file on Fedora in the past, it seems that this file in only for rpm-based releases. 
Maybe this is another problem?

**Comment by tfjmp** [comment]
Do check here for details: https://camflow.org/#installation

In short, it can work on Ubuntu, but we are not supporting it.

**Comment by HermitSun** [comment]
I will switch to Fedora.
Thank you for your excellent work! 🚀
