### ISSUE TITLE
I want to know about ipv4-egress & ipv4-ingress

### ISSUE THREAD

**Issue by morningphase** [CamFlow/camflow-dev#118]
when I try to run "sudo camflow --track-ipv4-egress 127.0.0.1/32:80 record ",the msg is"only apply to newly created connection"。So how can I use this command correctly？

**Comment by morningphase** [comment]
or sometimes “Could not change ipv4 egress.”  I genuinely want to know how to do this

**Comment by tfjmp** [comment]
The policy will only apply to sockets/connections created after the policy was set. If you have a connection already established it will not apply to it.

I don't have enough context to understand your second question.

**Comment by morningphase** [comment]
for example： sudo camflow -- track-ipv4-egress 127 .0.0.1 record，there will be：
Could not change ipv4 egress.
Unknown error - 22

**Comment by tfjmp** [comment]
the synthax is incorrect. Check `camflow -h` for the correct synthax.
