### ISSUE TITLE
curious about the camflow's output

### ISSUE THREAD

**Issue by morningphase** [CamFlow/camflow-dev#120]
In practice, I found that I sometimes didn't understand the output of CamFlow. I was curious that many times entities with different Uids, gids, inodes and prov:type "file" have the same UUID, while file entities with the same UUID may have different prov: label. In addition, I was wondering, is there a simple way in CamFlow to observe the actions or changes that have taken place in the same file entity or process?

**Comment by tfjmp** [comment]
It is UUID of the superblock.

The prove:id is unique to a "kernel object" (e.g. inode, processes etc.) and what you probably want to use.

**Comment by tfjmp** [comment]
More info there: https://camflow.org/#attributes

**Comment by tfjmp** [comment]
Closing as it seems to have answered the question.
