### ISSUE TITLE
about RELATIONS.md

### ISSUE THREAD

**Issue by morningphase** [CamFlow/camflow-dev#122]
I accidentally find that the term ‘perm_exec’ is not in the RELATIONS.md ? Is there any explanation?

**Comment by morningphase** [comment]
Moreover, more relation types such as mmap_exec_private are not described in  RELATIONS.md

**Comment by tfjmp** [comment]
Are you sure you are looking at the right release? If you look at [https://github.com/CamFlow/camflow-dev/blob/master/CHANGES.md] you will see it has changed across releases.

What is the version of CamFlow you are using?

**Comment by morningphase** [comment]
Now I see... I was checking my previously collected data and I wasn't aware of the exact version of CamFlow . It seems the CamFlow version is 0.7.2 because I see the edit history of RELATIONS.md and the aforementioned relation types have been removed. Now I guess there is no question any more.

**Comment by tfjmp** [comment]
No problem. You can pull the tag corresponding to the version you are using to get the list of relations. Let me know if you need further help.

Closing.
