### ISSUE TITLE
Identify known vulnerabilities

### ISSUE THREAD

**Issue by tfjmp** [CamFlow/camflow-dev#33]
Identify known vulnerabilities, looking through vulnerability databases. @michael-hahn should have URL of such website (please add link to this issue). It would also be interesting to identify type of vulnerability we can detect/we cannot. If not why? and can we do something about it?

**Comment by michael-hahn** [comment]
URLs of websites that host known vulnerabilities:
[https://cve.mitre.org/index.html](url)
[https://legalhackers.com](url)
[https://www.debian.org/Bugs/](url)
