### ISSUE TITLE
Possible concurrency issue.

### ISSUE THREAD

**Issue by michael-hahn** [CamFlow/camflow-dev#58]
When a multi-threaded program is running, the process `task` node may be associated (i.e., having edges with label `named_process`) with more than one `path` nodes.

As demonstrated in the figure below. The `[task]0` node is associated with two `[path]` nodes, both have the same path name `thread.o`.

This issue can be reproduced from time to time when running `thread.c` in the `CamFlow/examples/provenance` folder.

<img width="771" alt="screen shot 2018-02-13 at 2 30 32 pm" src="https://user-images.githubusercontent.com/9832528/36169538-7b2f93ac-10ca-11e8-96d5-3ad770ff47f6.png">

**Comment by tfjmp** [comment]
Michael, confirm the issue also occurs in SPADE? Do we have a graph for it?

**Comment by michael-hahn** [comment]
From what I have captured, SPADE contains such information only once. However, it does not have path nodes per se.
![thread](https://user-images.githubusercontent.com/9832528/36856695-9be9607e-1d44-11e8-9992-f895f44ff628.jpg)
