### ISSUE TITLE
`pckprov` lacks concreteness

### ISSUE THREAD

**Issue by michael-hahn** [CamFlow/camflow-dev#86]
This issue is related **only** to `tinkerbell` branch.

Current design that assigns content to pckprov using the address operator `&` is not ideal for `tinkerbell` design.

https://github.com/CamFlow/camflow-dev/blob/75523306e60371909e27d44c7fadad9af212a0e2/security/provenance/hooks.c#L2191

**Comment by tfjmp** [comment]
What would be a helpful form?

**Comment by michael-hahn** [comment]
Is it possible to have `provenance_parse_skb_ipv4` return the instance/pointer of `prov` instead of having `prov` as a parameter?
https://github.com/CamFlow/camflow-dev/blob/75523306e60371909e27d44c7fadad9af212a0e2/security/provenance/hooks.c#L2206

Ideally, after `pckprov` is declared in `provenance_socket_sock_rcv_skb`, it can be _assigned_ by `provenance_parse_skb_ipv4`.

**Comment by tfjmp** [comment]
https://github.com/CamFlow/camflow-dev/commit/66213a636c1c3a457d334a5c58e1e1619fe8b72c <<< change made in this commit.

**Comment by tfjmp** [comment]
@michael-hahn if ok, please close issue.
