### ISSUE TITLE
CamFlow's Retrieving Inode Security Field Should Not Result in Provenance Graph

### ISSUE THREAD

**Issue by michael-hahn** [CamFlow/camflow-dev#89]
`provenance_inode_getsecurity` retrieves inode's security field (for other purposes that should reflect in the provenance graph) should not result in a substructure in provenance graph.

**Comment by tfjmp** [comment]
https://github.com/CamFlow/camflow-dev/commit/406fecb9837107d3282d47f82fc98d5394b148d2 should be fixed by this commit.

@michael-hahn double check the change and close the issue if ok.

**Comment by michael-hahn** [comment]
**TinkerBell** shows that `provenance_inode_getsecurity` no longer generates provenance substructure. Close this issue.
