### ISSUE TITLE
Renaming Inode Should Have Its Distinct Relationship Subtype

### ISSUE THREAD

**Issue by michael-hahn** [CamFlow/camflow-dev#90]
Currently, `provenance_inode_rename` hook results in similar substructure as `provenance_inode_link` hook, both of which use `link` relationship subtype between `task`s and ` inode`s. This is not ideal as one cannot distinguish these two different actions from provenance graph.

**Comment by tfjmp** [comment]
https://github.com/CamFlow/camflow-dev/commit/cd0078a0158af97e5dd605d13ee13137552affa3 should have fixed the issue.

@michael-hahn please double check that it is ok and close the issue!

**Comment by michael-hahn** [comment]
**TinkerBell* shows that `provenance_inode_rename` now has `rename` relationship subtype while `provenance_inode_link` has `link` relationship subtype. Close this issue.
