### ISSUE TITLE
Provenance Inode Extra Attributes Setting Bookkeeping Should Not Be Reflected in Provenance Graph

### ISSUE THREAD

**Issue by michael-hahn** [CamFlow/camflow-dev#91]
`provenance_inode_setxattr` should not result in substructure in provenance graph as this hook is an internal bookkeeping action.

**Comment by tfjmp** [comment]
https://github.com/CamFlow/camflow-dev/commit/b9cb3205dcf05680f155701f891f535f6778f167 should be fixing this issue.

@michael-hahn check if this is the case and close the issue if it works.

**Comment by michael-hahn** [comment]
**TinkerBell** shows that `provenance_inode_setxattr` no longer has any provenance substructure associated to it. Close this issue.
