### ISSUE TITLE
CamFlow's Bookkeeping for Socket Security Field Should Not Be Reflected in Provenance Graph 

### ISSUE THREAD

**Issue by michael-hahn** [CamFlow/camflow-dev#93]
`provenance_sk_alloc_security` hook is for setting up CamFlow's security bookkeeping, which should not result in any provenance subgraph.

**Comment by tfjmp** [comment]
https://github.com/CamFlow/camflow-dev/commit/071e407a9556ac0180374a7e047c0d1fa342926e this should fix the issue.

@michael-hahn please double check and close if it works!

**Comment by michael-hahn** [comment]
**TinkerBell** confirms that `provenance_sk_alloc_security` is empty. Close this issue for now.
