### ISSUE TITLE
Unix Stream Connect and Socket Connect Should Have Distinct Relationship Names

### ISSUE THREAD

**Issue by michael-hahn** [CamFlow/camflow-dev#94]
Currently, `provenance_unix_stream_connect` and `provenance_socket_connect` have identical `connect` relationship subtype between `task`s and `inode`s, which makes it impossible to differentiate these two hooks in a provenance graph. A different subtype name should be preferred.

**Comment by tfjmp** [comment]
https://github.com/CamFlow/camflow-dev/commit/24181a46ad19a8bd8e6b989e2af79c7e3e6c2b37 should fix the issue.

@michael-hahn please double check and close the issue if it is ok!

**Comment by michael-hahn** [comment]
**TinkerBell** shows that `provenance_unix_stream_connect` now has `connect_unix_stream` subtype while `provenance_socket_connect` has `connect` subtype. Close this issue.
